export const AppConfig = {
    appTitle: '',
    brandName: '',
    copyRight: '',
    apiBaseUrl: 'http://localhost/ci-emp-portal-api/api/',
    useMockServer: false
};

export const apiUrl = {
    authenticate: AppConfig.apiBaseUrl + 'user/authenticate',
    checkEmail: AppConfig.apiBaseUrl + 'user/checkEmail',
    getUsers: AppConfig.apiBaseUrl + 'user/users',
    dashboardStat: AppConfig.apiBaseUrl + 'user/dashboardStat',
    userFormData: AppConfig.apiBaseUrl + 'user/userFormData',
    addUser: AppConfig.apiBaseUrl + 'user/users',
    editUser: AppConfig.apiBaseUrl + 'user/users',
    deleteUser: AppConfig.apiBaseUrl + 'user/users',
    userDetails: AppConfig.apiBaseUrl + 'user/userDetails',
    changePassword: AppConfig.apiBaseUrl + 'user/changePassword',
    userData: AppConfig.apiBaseUrl + 'user/userData',
    updateUserData: AppConfig.apiBaseUrl + 'user/updateUserData',
    getAddress: AppConfig.apiBaseUrl + 'address',
    addAddress: AppConfig.apiBaseUrl + 'address',
    updateAddress: AppConfig.apiBaseUrl + 'address',
    deleteAddress: AppConfig.apiBaseUrl + 'address',
    academicFormData: AppConfig.apiBaseUrl + 'academic/formData',
    getEducation: AppConfig.apiBaseUrl + 'academic',
    addEducation: AppConfig.apiBaseUrl + 'academic',
    updateEducation: AppConfig.apiBaseUrl + 'academic',
    deleteEducation: AppConfig.apiBaseUrl + 'academic',
    getExperience: AppConfig.apiBaseUrl + 'user/getExperience',
    addExperience: AppConfig.apiBaseUrl + 'user/addExperience',
    updateExperience: AppConfig.apiBaseUrl + 'user/updateExperience',
    deleteExperience: AppConfig.apiBaseUrl + 'user/deleteExperience',
    getPayroll: AppConfig.apiBaseUrl + 'user/getPayroll',
    addPayroll: AppConfig.apiBaseUrl + 'user/addPayroll',
    updatePayroll: AppConfig.apiBaseUrl + 'user/updatePayroll',
    deletePayroll: AppConfig.apiBaseUrl + 'user/deletePayroll',
    getEmergencyContact: AppConfig.apiBaseUrl + 'user/getEmergencyContact',
    addEmergencyContact: AppConfig.apiBaseUrl + 'user/addEmergencyContact',
    updateEmergencyContact: AppConfig.apiBaseUrl + 'user/updateEmergencyContact',
    deleteEmergencyContact: AppConfig.apiBaseUrl + 'user/deleteEmergencyContact',
};
